version: '3'
networks:
  app-network:
    external: false
services:
  redis:
    image: redis_db
    container_name: redis_db
    build:
      context: redis-server
    ports:
      - "1234:1234"
    networks:
      - app-network
  back1:
    image: sma-back
    container_name: back1
    environment:
      - REDIS_HOST=redis_db
      - APPID=1111
      - RABBITMQ_URL=amqp://rabbitmq:5672
    build: .
    networks:
      - app-network
    depends_on:
      - redis
    ports:
      - "8001:8000"
  back2:
    image: sma-back
    container_name: back2
    environment:
      - REDIS_HOST=redis_db
      - APPID=2222
      - RABBITMQ_URL=amqp://rabbitmq:5672
    build: .
    networks:
      - app-network
    depends_on:
      - redis
    ports:
       - "8002:8000"
  back3:
    image: sma-back
    container_name: back3
    environment:
      - REDIS_HOST=redis_db
      - APPID=3333
      - RABBITMQ_URL=amqp://rabbitmq:5672
    build: .
    networks:
      - app-network
    depends_on:
      - redis
    ports:
      - "8003:8000"
  back4:
    image: sma-back
    container_name: back4
    environment:
      - REDIS_HOST=redis_db
      - APPID=4444
      - RABBITMQ_URL=amqp://rabbitmq:5672
    build: .
    networks:
      - app-network
    depends_on:
      - redis
    ports:
      - "8004:8000"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - app-network
